version: 2
branches:
  only:
    - dev
    - master
jobs:
  build:
    working_directory: /app
    docker:
      - image: andreilupu/headless-chrome-shots:latest
    steps:
      - run: cd /app && mkdir ss && ls
      - run: cd /app && node shot.js --url=https://andrei-lupu.com --out=ss/shot.png

      - store_artifacts:
          path: /app/ss/
          destination: artifact-file